services:
  postgres:
    image: postgres:16-alpine
    container_name: taskhub_postgres
    environment:
      POSTGRES_USER: taskhub
      POSTGRES_PASSWORD: taskhub
      POSTGRES_DB: taskhub
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  api:
    container_name: taskhub_api
    build:
      context: .
      dockerfile: Dockerfile.dev
    tty: true
    command: yarn workspace @taskhub/api dev
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.container
    depends_on:
      - postgres

volumes:
  taskhub_pgdata:
