query GetTasks {
  tasks {
    id
    title
    description
    status
    priority
    deadline
    createdAt
  }
}

query GetTaskStats {
  taskStats {
    total
    todo
    inProgress
    done
    overdue
  }
}

mutation CreateTask($input: CreateTaskInput!) {
  createTask(input: $input) {
    id
  }
}

mutation DeleteTask($id: ID!) {
  deleteTask(id: $id)
}

mutation UpdateTaskStatus($input: UpdateTaskStatusInput!) {
  updateTaskStatus(input: $input) {
    id
  }
}
